### ISSUE TITLE
Snippet with newlines

### ISSUE THREAD

**Issue by savinoda** [inkarkat/vim-EntryComplete#1]
**Motivation**

The snippet to be inserted in the document can't contain new lines. This plugin is very useful to quickly insert lines of text in any programming language but if it cannot contain newlines is quite bad

**Request and Purpose**

Is there a way to insert new lines in the snippet to be inserted in the doc?

**Comment by inkarkat** [comment]
I mostly use single words for entries, at most a few words for a single entry; the main benefit is in the easy setup (through the plugin's conventions) and the ability to provide additional information that is shown during completion, to support me in choosing the right entry. For example, I've defined _Spring stereotypes_ in `~/.vim/entries/java/spring-stereotypes.txt`, because I often mix them up:

```
words	menu
@Component	generic stereotype for any Spring-managed component
@Repository	stereotype for persistence layer
@Service	stereotype for service layer
@Controller	stereotype for presentation layer (spring-mvc)
```

That's the reason why the entry definitions are line-based. This would have to be changed to support multi-line entries, or alternatively, an escaping mechanism (e.g. `\n`) would need to be introduced.

The next problem is that Vim does not support insert-mode completion of text that spans multiple lines; any newline character gets inserted as a literal `^M` character. Though there are ways to extend Vim to handle this [in my private completion customization](https://github.com/inkarkat/vim-ingocompletion/blob/d93d443e1ac192e12c9fe51353715d691a619017/plugin/ingocompletion.vim#L74-L132), I would regard this as a crude hack, nothing to build a plugin on. So ideally, Vim would first support this natively, before completion plugins pick this up.

---

I think you're rather looking for a _snippets plugin_ - you're even calling the objects snippets instead of entries! These usually also support multiple cursor stops inside the snippet, and template locations, etc. - all things that this plugin doesn't want to be concerned with.

With regards to completion of the snippet name, some snippet plugins offer that already, or for example _snipMate_ can be extended with that through my plugin combination of
* [SnippetComplete plugin](http://www.vim.org/scripts/script.php?script_id=2926)
* [SnippetCompleteSnipMate plugin](http://www.vim.org/scripts/script.php?script_id=4276)

The only downside vs. this plugin would be that first only the snippet name would be completed, and then the snippet expansion would follow (usually triggered via another key).

**Comment by inkarkat** [comment]
_snippets_ are like the built-in `:abbreviate` on steroids, usually with parameter insertions, mirroring, and multiple stops inside them. One of the first, very famous (and still widely used) Vim plugins is [snipMate](https://www.vim.org/scripts/script.php?script_id=2540) (inspired by the _TextMate_ editor); unfortunately, it's not maintained any more; though there is [a fork](https://github.com/garbas/vim-snipmate). A modern alternative (that requires Python though) is [UltiSnips](https://www.vim.org/scripts/script.php?script_id=2715). There are more, see [this list on the Vim Tips Wiki](http://vim.wikia.com/wiki/Category:Automated_Text_Insertion) and [this comparison by Mark Weber](http://vim-wiki.mawercer.de/wiki/topic/text-snippets-skeletons-templates.html).

There are three things to evaluate: First, the features of the snippet engine itself, second, the quality and breadth of snippets provided by the author or others; third, how easy it is to add new snippets.

**Comment by savinoda** [comment]
Got it... thanks for your answer... Indeed this was very very easy to setup... I workaround would be to encode newlines with some sequence of characters (e.g., @@@)... before calling the autocomplete saving the current position in a marker, and after the autocomplete is done calling a function that replaces @@@ with new lines.I'm currently able to perform the marking before the autocomplete happens but I still need to figure out how to call another function after the autocomplete is done... I could do it manually with another binding but it's not optimal

**Comment by inkarkat** [comment]
Right, you can hack something together like that (I've implemented the newline expansion after completion [here](https://github.com/inkarkat/vim-ingocompletion/blob/d93d443e1ac192e12c9fe51353715d691a619017/plugin/ingocompletion.vim#L74-L132)), but I would really recommend you try out a snippet plugin as an alternive first - I think it's a much better fit.
